import Link from "next/link";
import { Search, Users } from "lucide-react";
import { PageHeader } from "@/components/ui";
import { getCustomers } from "@/lib/services/customers";
import { initials, money, shortDate } from "@/lib/utils";

export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q } = await searchParams; const customers = getCustomers(q);
  return <><PageHeader eyebrow="Relationships" title="Customers" description={`${customers.length} customer profiles with verified purchase history.`} action={<div className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-xs font-semibold"><Users size={16} className="text-moss"/> 8 new this month</div>}/><form className="card mb-5 flex gap-3 p-4"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-stone-400" size={16}/><input name="q" defaultValue={q} className="input w-full pl-9" placeholder="Search name, email or phone…"/></label><button className="btn-primary">Search</button></form><div className="table-shell overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="border-b bg-stone-50/70 text-[10px] uppercase tracking-wider text-stone-400"><tr><th className="px-6 py-4">Customer</th><th className="px-4 py-4">Contact</th><th className="px-4 py-4">Purchases</th><th className="px-4 py-4">Last purchase</th><th className="px-6 py-4 text-right">Lifetime value</th></tr></thead><tbody>{customers.map((customer, index) => <tr key={customer.id} className="table-row text-xs"><td className="px-6 py-4"><Link href={`/customers/${customer.id}`} className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-full text-[11px] font-bold ${index%3===0?"bg-[#e9dfcf] text-[#765e40]":index%3===1?"bg-[#dce5de] text-moss":"bg-[#e7dcd8] text-rust"}`}>{initials(customer.name)}</span><span><span className="block font-semibold">{customer.name}</span><span className="text-[10px] text-stone-400">Customer since {shortDate(customer.createdAt)}</span></span></Link></td><td className="px-4 py-4"><div>{customer.email}</div><div className="mt-1 text-[10px] text-stone-400">{customer.phone}</div></td><td className="px-4 py-4 font-semibold">{customer.purchaseCount}</td><td className="px-4 py-4 text-stone-500">{customer.lastPurchase ? shortDate(customer.lastPurchase) : "—"}</td><td className="px-6 py-4 text-right font-bold">{money(customer.totalSpent)}</td></tr>)}</tbody></table></div></>;
}
