import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CheckCircle2, CreditCard } from "lucide-react";
import { Badge, statusTone } from "@/components/ui";
import { getSale } from "@/lib/services/sales";
import { dateTime, money } from "@/lib/utils";

export default async function SalePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const sale = getSale(id); if (!sale) notFound();
  return <div className="mx-auto max-w-4xl"><Link href="/sales" className="mb-6 inline-flex items-center gap-2 text-xs font-semibold text-stone-500"><ArrowLeft size={15}/>Back to sales</Link><div className="card overflow-hidden"><div className="flex flex-col justify-between gap-4 border-b bg-stone-50/60 p-7 sm:flex-row"><div><div className="text-[10px] font-bold uppercase tracking-widest text-stone-400">Sales receipt</div><h1 className="mt-2 font-serif text-4xl font-bold">Order {sale.number}</h1><p className="mt-1 text-xs text-stone-500">{dateTime(sale.createdAt)}</p></div><div className="text-left sm:text-right"><Badge tone={statusTone(sale.status)}>{sale.status}</Badge><div className="mt-3 font-serif text-3xl font-bold">{money(sale.total)}</div></div></div><div className="grid gap-6 p-7 md:grid-cols-2"><div><div className="label">Customer</div><Link href={`/customers/${sale.customerId}`} className="font-serif text-2xl font-semibold hover:text-rust">{sale.customerName}</Link></div><div><div className="label">Payment method</div><div className="flex items-center gap-2 text-sm font-semibold capitalize"><CreditCard size={16}/>{sale.paymentMethod}</div></div></div><div className="border-y"><div className="grid grid-cols-[1fr_auto_auto] gap-4 bg-stone-50 px-7 py-3 text-[10px] font-bold uppercase tracking-wider text-stone-400"><span>Item</span><span>Qty</span><span className="w-24 text-right">Subtotal</span></div>{sale.items.map((item)=><div key={item.id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-t px-7 py-5 text-xs"><div><div className="font-semibold">{item.productName}</div><div className="mt-1 text-[10px] text-stone-400">{money(item.unitPrice)} each</div></div><div>{item.quantity}</div><div className="w-24 text-right font-bold">{money(item.subtotal)}</div></div>)}</div><div className="ml-auto w-full max-w-sm space-y-3 p-7 text-xs"><div className="flex justify-between"><span className="text-stone-500">Subtotal</span><span>{money(sale.subtotal)}</span></div><div className="flex justify-between"><span className="text-stone-500">Discount</span><span className="text-rust">− {money(sale.discount)}</span></div><div className="flex justify-between border-t pt-4 font-serif text-xl font-bold"><span>Total</span><span>{money(sale.total)}</span></div></div>{sale.status==="completed"&&<div className="flex items-center gap-2 bg-emerald-50 px-7 py-4 text-xs font-semibold text-emerald-700"><CheckCircle2 size={16}/>This transaction is complete and reflected in inventory.</div>}</div></div>;
}
