import Link from "next/link";
import { CreditCard, Search, ShoppingBag } from "lucide-react";
import { Badge, PageHeader, statusTone } from "@/components/ui";
import { getSales } from "@/lib/services/sales";
import { dateTime, money } from "@/lib/utils";

export default async function SalesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const sales = getSales({ customer: params.customer, status: params.status, date: params.date }); const revenue = sales.filter(s=>s.status==="completed").reduce((a,s)=>a+s.total,0);
  return <><PageHeader eyebrow="Transactions" title="Sales" description={`${sales.length} orders · ${money(revenue)} in completed revenue.`} action={<div className="rounded-xl bg-moss px-4 py-2.5 text-xs font-semibold text-white"><CreditCard size={15} className="mr-2 inline"/>Payments healthy</div>}/><form className="card mb-5 flex flex-col gap-3 p-4 md:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-stone-400" size={16}/><input name="customer" defaultValue={params.customer} className="input w-full pl-9" placeholder="Customer name…"/></label><input type="date" name="date" defaultValue={params.date} className="input"/><select name="status" defaultValue={params.status} className="input"><option value="">All statuses</option><option value="completed">Completed</option><option value="pending">Pending</option><option value="refunded">Refunded</option></select><button className="btn-primary">Filter</button></form><div className="table-shell overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="border-b bg-stone-50 text-[10px] uppercase tracking-wider text-stone-400"><tr><th className="px-6 py-4">Order</th><th className="px-4 py-4">Customer</th><th className="px-4 py-4">Items</th><th className="px-4 py-4">Payment</th><th className="px-4 py-4">Status</th><th className="px-6 py-4 text-right">Total</th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id} className="table-row text-xs"><td className="px-6 py-4"><Link href={`/sales/${sale.id}`} className="font-bold">{sale.number}</Link><div className="mt-1 text-[10px] text-stone-400">{dateTime(sale.createdAt)}</div></td><td className="px-4 py-4 font-medium"><Link href={`/customers/${sale.customerId}`}>{sale.customerName}</Link></td><td className="px-4 py-4"><span className="inline-flex items-center gap-1"><ShoppingBag size={13}/>{sale.items.reduce((a,i)=>a+i.quantity,0)}</span></td><td className="px-4 py-4 capitalize text-stone-500">{sale.paymentMethod}</td><td className="px-4 py-4"><Badge tone={statusTone(sale.status)}>{sale.status}</Badge></td><td className="px-6 py-4 text-right font-bold">{money(sale.total)}</td></tr>)}</tbody></table></div></>;
}
