import Image from "next/image";
import Link from "next/link";
import { Headphones, PackageCheck, RotateCcw, ShieldCheck } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { getProducts } from "@/lib/services/products";

export default function HomePage() {
  const products=getProducts().filter(product=>product.stock-product.reservedStock>0); const arrivals=products.slice(0,8);
  return <>
    <section className="px-3 pb-10 pt-3 sm:px-4 md:px-8 md:pb-12 md:pt-4 lg:px-14"><div className="relative mx-auto min-h-[500px] max-w-[1796px] overflow-hidden rounded-xl md:min-h-[650px]"><Image src="/editorial/hero-relic.png" alt="Colección de ropa vintage RELIC" fill priority className="object-cover object-[67%_center]"/><div className="absolute inset-0 bg-gradient-to-r from-black/55 via-black/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-white sm:max-w-xl sm:p-8 md:p-16"><p className="text-xs font-semibold sm:text-sm">Renová tu guardarropa</p><h1 className="mt-3 text-4xl font-bold tracking-[-.04em] sm:text-5xl md:text-7xl">La selección vintage</h1><p className="mt-4 max-w-md text-sm leading-6 text-white/85">Piezas únicas seleccionadas por su calidad, carácter y una segunda vida.</p><Link href="/products?sort=new" className="mt-6 inline-flex min-h-12 items-center rounded-full bg-white px-7 text-sm font-semibold text-black transition hover:bg-black hover:text-white sm:mt-7 sm:px-9">Ver colección</Link></div></div></section>

    <section className="px-5 py-14 md:px-10 md:py-20"><div className="mx-auto max-w-[1300px]"><div className="mb-9 text-center"><h2 className="text-3xl font-bold tracking-tight md:text-4xl">Nuevos ingresos</h2><p className="mt-2 text-sm text-stone-500">Hallazgos vintage de marcas que ya son un clásico</p></div><div className="grid grid-cols-2 gap-x-4 gap-y-9 md:grid-cols-3 lg:grid-cols-4">{arrivals.map((product,index)=><ProductCard key={product.id} product={product} priority={index<4}/>)}</div><div className="mt-12 text-center"><Link href="/products" className="store-button-light">Ver todas las prendas</Link></div></div></section>

    <section className="px-5 py-14 md:px-10 md:py-20"><div className="mx-auto max-w-[1300px]"><div className="mb-9 text-center"><h2 className="text-3xl font-bold tracking-tight md:text-4xl">Comprar por colección</h2><p className="mt-2 text-sm text-stone-500">Tres selecciones, infinitas formas de usarlas</p></div><div className="grid gap-5 md:grid-cols-3"><CollectionCard image="/editorial/worn-leather.png" title="Archivo de cuero" subtitle="Hecho para durar" href="/products?q=leather"/><CollectionCard image="/editorial/track-archive.png" title="Deporte de los 90" subtitle="De vuelta en rotación" href="/products?q=track"/><CollectionCard image="/editorial/hero-relic.png" title="Denim de todos los días" subtitle="El calce perfecto" href="/products?category=Jeans"/></div></div></section>

    <section className="bg-[#f5f5f3] px-5 py-16 md:px-10"><div className="mx-auto grid max-w-[1300px] gap-8 md:grid-cols-4"><Feature icon={PackageCheck} title="Envío gratis" text="En compras superiores a US$180"/><Feature icon={RotateCcw} title="Devoluciones simples" text="Tenés 14 días para devolver"/><Feature icon={ShieldCheck} title="Calidad revisada" text="Inspeccionamos cada prenda"/><Feature icon={Headphones} title="Estamos para ayudarte" text="Atención personalizada siempre"/></div></section>

    <section className="px-5 py-20 text-center md:px-10 md:py-28"><div className="mx-auto max-w-xl"><p className="text-sm font-semibold">Sumate a nuestra comunidad</p><h2 className="mt-3 text-4xl font-bold tracking-tight md:text-5xl">Elegí primero.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-stone-500">Nuevos ingresos, notas de estudio y lanzamientos especiales de vez en cuando.</p><form className="mx-auto mt-7 flex max-w-md flex-col gap-2 rounded-3xl border border-stone-300 bg-white p-1.5 sm:flex-row sm:rounded-full sm:gap-0"><input type="email" className="min-h-11 min-w-0 flex-1 bg-transparent px-4 text-sm outline-none" placeholder="Ingresá tu email"/><button className="min-h-11 rounded-full bg-black px-6 py-3 text-xs font-semibold text-white">Suscribirme</button></form></div></section>
  </>;
}

function CollectionCard({image,title,subtitle,href}:{image:string;title:string;subtitle:string;href:string}) { return <Link href={href} className="group relative aspect-[4/5] overflow-hidden rounded-xl bg-stone-200"><Image src={image} alt={title} fill className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-white"><p className="text-sm">{subtitle}</p><h3 className="mt-1 text-3xl font-bold">{title}</h3><span className="mt-5 inline-flex rounded-full bg-white px-6 py-3 text-xs font-semibold text-black">Comprar ahora</span></div></Link>; }
function Feature({icon:Icon,title,text}:{icon:typeof PackageCheck;title:string;text:string}) { return <div className="flex items-center gap-4 md:flex-col md:text-center"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-white"><Icon size={21} strokeWidth={1.5}/></span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs text-stone-500">{text}</p></div></div>; }
