import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Mail, Phone, ShoppingBag, Wallet } from "lucide-react";
import { Badge, statusTone } from "@/components/ui";
import { getCustomer } from "@/lib/services/customers";
import { initials, money, shortDate } from "@/lib/utils";

export default async function CustomerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const customer = getCustomer(id); if (!customer) notFound();
  return <div className="mx-auto max-w-6xl"><Link href="/customers" className="mb-6 inline-flex items-center gap-2 text-xs font-semibold text-stone-500"><ArrowLeft size={15}/>Back to customers</Link><div className="grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="card h-fit p-6"><div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-moss text-xl font-bold text-white">{initials(customer.name)}</div><h1 className="mt-5 font-serif text-3xl font-semibold">{customer.name}</h1><p className="mt-1 text-xs text-stone-400">Customer since {shortDate(customer.createdAt)}</p><div className="mt-6 space-y-4 border-t pt-5"><div className="flex items-center gap-3 text-xs"><Mail size={15} className="text-stone-400"/><span className="truncate">{customer.email}</span></div><div className="flex items-center gap-3 text-xs"><Phone size={15} className="text-stone-400"/>{customer.phone}</div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-stone-50 p-3"><ShoppingBag size={16} className="text-moss"/><div className="mt-2 font-serif text-2xl font-bold">{customer.purchaseCount}</div><div className="text-[9px] uppercase tracking-wider text-stone-400">Purchases</div></div><div className="rounded-xl bg-stone-50 p-3"><Wallet size={16} className="text-rust"/><div className="mt-2 font-serif text-2xl font-bold">{money(customer.totalSpent)}</div><div className="text-[9px] uppercase tracking-wider text-stone-400">Total spent</div></div></div></aside><section className="table-shell"><div className="p-6"><h2 className="font-serif text-3xl">Purchase history</h2><p className="mt-1 text-xs text-stone-500">Every transaction associated with this customer.</p></div><div className="overflow-x-auto"><table className="w-full text-left"><thead className="border-y bg-stone-50 text-[10px] uppercase tracking-wider text-stone-400"><tr><th className="px-6 py-3">Order</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Items</th><th className="px-4 py-3">Status</th><th className="px-6 py-3 text-right">Total</th></tr></thead><tbody>{customer.purchases.map((sale) => <tr key={sale.id} className="table-row text-xs"><td className="px-6 py-4 font-bold"><Link href={`/sales/${sale.id}`}>{sale.number}</Link></td><td className="px-4 py-4 text-stone-500">{shortDate(sale.createdAt)}</td><td className="px-4 py-4">{sale.items.length}</td><td className="px-4 py-4"><Badge tone={statusTone(sale.status)}>{sale.status}</Badge></td><td className="px-6 py-4 text-right font-bold">{money(sale.total)}</td></tr>)}</tbody></table></div></section></div></div>;
}
