"use client";
import { FormEvent, useState } from "react";
import { CalendarPlus, X, XCircle } from "lucide-react";

export function NewReservation({ customers, products }: { customers: {id:string;name:string}[]; products:{id:string;name:string;size:string;stock:number;reservedStock:number}[] }) {
  const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const values=Object.fromEntries(new FormData(e.currentTarget));const response=await fetch("/api/v1/reservations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...values,quantity:Number(values.quantity)})});if(response.ok){setMessage("Reservation created");setTimeout(()=>window.location.reload(),500)}else{setMessage((await response.json()).error||"Could not create");setSaving(false)}}
  return <><button className="btn-primary" onClick={()=>setOpen(true)}><CalendarPlus size={16}/>New reservation</button>{open&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/45 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-6"><div><h2 className="font-serif text-3xl">Create reservation</h2><p className="text-xs text-stone-500">Hold an available item for 48 hours.</p></div><button type="button" onClick={()=>setOpen(false)}><X size={19}/></button></div><div className="space-y-4 p-6"><label><span className="label">Customer</span><select className="input w-full" name="customerId" required><option value="">Select a customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="label">Product</span><select className="input w-full" name="productId" required><option value="">Select an available product</option>{products.filter(p=>p.stock-p.reservedStock>0).map(p=><option key={p.id} value={p.id}>{p.name} · {p.size} ({p.stock-p.reservedStock} left)</option>)}</select></label><label><span className="label">Quantity</span><input className="input w-full" type="number" min="1" defaultValue="1" name="quantity" required/></label><div className="rounded-xl bg-amber-50 p-3 text-xs leading-relaxed text-amber-800">Stock is reserved immediately. Cancelling the reservation automatically releases it.</div><div className="flex items-center justify-end gap-3 border-t pt-5"><span className="mr-auto text-xs text-stone-500">{message}</span><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" disabled={saving}>{saving?"Creating…":"Create hold"}</button></div></div></form></div>}</>;
}

export function CancelReservation({ id }: { id:string }) { const [busy,setBusy]=useState(false); async function cancel(){if(!window.confirm("Cancel this reservation and release its stock?"))return;setBusy(true);const r=await fetch(`/api/v1/reservations/${id}`,{method:"DELETE"});if(r.ok)window.location.reload();else setBusy(false)} return <button onClick={cancel} disabled={busy} className="inline-flex items-center gap-1 text-[10px] font-bold text-red-600 hover:underline"><XCircle size={13}/>{busy?"Cancelling…":"Cancel"}</button> }
