import Link from "next/link";
import { SlidersHorizontal } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { categoryLabel } from "@/lib/utils";
import { getProductOptions, searchProducts } from "@/lib/services/products";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params=await searchParams; let products=searchProducts({q:params.q,category:params.category,size:params.size,inStock:params.inStock!=="false"});
  if(params.sort==="price-low") products=[...products].sort((a,b)=>a.price-b.price);
  if(params.sort==="price-high") products=[...products].sort((a,b)=>b.price-a.price);
  if(params.sort==="new") products=[...products].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());
  const options=getProductOptions();
  const title=params.category ? categoryLabel(params.category) : params.q ? `Resultados para “${params.q}”` : "Tienda";
  return <div className="px-5 pb-24 pt-12 md:px-10 md:pt-20"><div className="mx-auto max-w-[1450px]"><div className="flex flex-col justify-between gap-6 border-b border-stone-300 pb-10 md:flex-row md:items-end"><div><div className="text-[9px] font-bold uppercase tracking-[.2em] text-rust">La colección</div><h1 className="mt-3 editorial-serif text-5xl md:text-7xl">{title}</h1><p className="mt-3 text-xs text-stone-500">{products.length} piezas únicas, revisadas y listas para usar.</p></div><form className="flex flex-wrap gap-2"><input type="hidden" name="category" value={params.category||""}/><input name="q" type="search" defaultValue={params.q||""} placeholder="Buscar en la colección" aria-label="Buscar en la colección" className="h-11 min-w-48 border border-stone-300 bg-transparent px-4 text-xs outline-none placeholder:text-stone-400 focus:border-ink"/><select name="size" defaultValue={params.size} className="h-11 border border-stone-300 bg-transparent px-4 text-[10px] font-bold uppercase tracking-wider"><option value="">Todos los talles</option>{options.sizes.map(size=><option key={size}>{size}</option>)}</select><select name="sort" defaultValue={params.sort} className="h-11 border border-stone-300 bg-transparent px-4 text-[10px] font-bold uppercase tracking-wider"><option value="new">Más recientes</option><option value="price-low">Precio: menor a mayor</option><option value="price-high">Precio: mayor a menor</option></select><button className="flex h-11 items-center gap-2 bg-ink px-4 text-[10px] font-bold uppercase tracking-wider text-white"><SlidersHorizontal size={14}/>Aplicar</button></form></div><div className="no-scrollbar mt-6 flex gap-2 overflow-x-auto pb-2"><Link href="/products" className={`shrink-0 rounded-full border px-5 py-2.5 text-[9px] font-bold uppercase tracking-wider ${!params.category?"border-ink bg-ink text-white":"border-stone-300"}`}>Todo</Link>{options.categories.map(category=><Link key={category} href={`/products?category=${category}`} className={`shrink-0 rounded-full border px-5 py-2.5 text-[9px] font-bold uppercase tracking-wider ${params.category===category?"border-ink bg-ink text-white":"border-stone-300"}`}>{categoryLabel(category)}</Link>)}</div>{products.length?<div className="mt-10 grid grid-cols-2 gap-x-3 gap-y-9 md:grid-cols-3 md:gap-x-5 lg:grid-cols-4">{products.map((product,index)=><ProductCard key={product.id} product={product} priority={index<4}/>)}</div>:<div className="py-32 text-center"><h2 className="editorial-serif text-4xl">Esta vez no encontramos nada.</h2><p className="mt-3 text-xs text-stone-500">El vintage es impredecible. Probá otro talle o colección.</p><Link href="/products" className="store-button mt-7">Limpiar filtros</Link></div>}</div></div>;
}
