import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Leaf, Package, Ruler } from "lucide-react";

export default function StoryPage() { return <>
  <section className="grid min-h-[75vh] lg:grid-cols-2"><div className="flex min-w-0 items-center px-5 py-16 sm:px-7 sm:py-20 md:px-16 lg:px-[9vw]"><div className="min-w-0 max-w-xl"><div className="text-[9px] font-bold uppercase tracking-[.22em] text-rust">Nuestra historia</div><h1 className="mt-4 break-words text-balance editorial-serif text-5xl leading-[.9] sm:text-6xl md:text-8xl">La mejor ropa ya existe.</h1><p className="mt-7 max-w-lg text-sm leading-7 text-stone-600">RELIC nació de una idea simple: lo que elegimos vestir puede tener pasado sin quedarse detenido en él. Buscamos piezas de materiales honestos, siluetas seguras y el carácter suficiente para ser parte de tu propia historia.</p></div></div><div className="relative min-h-[60vh]"><Image src="/editorial/worn-leather.png" alt="Selección vintage de cuero RELIC" fill priority className="object-cover"/></div></section>
  <section className="bg-ink px-5 py-20 text-white sm:px-6 md:px-10 md:py-28"><div className="mx-auto grid min-w-0 max-w-[1300px] gap-14 lg:grid-cols-[1fr_1.25fr]"><div className="min-w-0"><div className="text-[9px] font-bold uppercase tracking-[.2em] text-rust">Cómo seleccionamos</div><h2 className="mt-4 break-words editorial-serif text-4xl leading-none sm:text-5xl md:text-7xl">Despacio, con cuidado y personalmente.</h2></div><div className="grid min-w-0 gap-px bg-white/15 sm:grid-cols-2">{[["01","Encontramos","En comercios independientes, guardarropas privados y archivos olvidados."],["02","Inspeccionamos","Costuras, herrajes, telas y cada señal de uso se revisan a mano."],["03","Restauramos","Limpiamos cada pieza y hacemos reparaciones pequeñas sin borrar su historia."],["04","Describimos","Las medidas y las notas de estado son honestas, útiles y específicas."]].map(([n,title,text])=><div key={n} className="min-w-0 bg-ink p-7 md:p-9"><div className="text-[9px] text-stone-600">{n}</div><h3 className="mt-8 editorial-serif text-2xl">{title}</h3><p className="mt-3 text-xs leading-6 text-stone-400">{text}</p></div>)}</div></div></section>
  <section className="grid bg-[#d9d0c2] lg:grid-cols-2"><div className="relative min-h-[65vh]"><Image src="/editorial/track-archive.png" alt="Selección RELIC de camperas deportivas" fill className="object-cover"/></div><div className="flex min-w-0 items-center px-5 py-20 sm:px-7 md:px-16 lg:px-[9vw]"><div className="min-w-0"><Leaf strokeWidth={1.2} size={30}/><h2 className="mt-6 break-words text-balance editorial-serif text-4xl leading-none sm:text-5xl md:text-6xl">Una huella más liviana, sin sermones.</h2><p className="mt-6 max-w-lg text-sm leading-7 text-stone-600">Mantener en uso una buena prenda es un acto práctico de cuidado. Usamos empaques reciclados, evitamos el plástico innecesario y nunca pretendemos que comprar más sea la respuesta. Comprá la pieza que te encanta. Usala mucho. Pasala bien.</p><Link href="/products" className="store-button mt-8 h-auto min-h-12 px-6 py-3 text-center leading-5">Explorar la colección <ArrowRight size={14}/></Link></div></div></section>
  <section id="sizing" className="scroll-mt-28 px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-[1200px]"><div className="grid gap-10 md:grid-cols-3"><Info icon={Ruler} title="Talles vintage" text="Los talles de etiqueta cambian entre décadas, por eso medimos cada prenda en plano. Compará nuestras medidas con una prenda que ya tengas y te quede bien."/><Info icon={Check} title="Cómo describimos el estado" text="Excelente significa casi sin uso; muy bueno admite señales sutiles del paso del tiempo; bueno celebra el carácter visible. Siempre describimos cualquier detalle relevante."/><Info icon={Package} title="Envíos y devoluciones" text="Los pedidos salen de nuestro estudio dentro de dos días hábiles. Tenés 14 días desde la entrega para devolver una prenda sin usar."/></div></div></section>
  <section id="shipping" className="bg-rust px-5 py-20 text-center text-white sm:px-6"><h2 className="break-words editorial-serif text-4xl sm:text-5xl">¿Lista para encontrar la tuya?</h2><Link href="/products" className="mt-7 inline-flex min-h-12 items-center bg-white px-6 py-3 text-[9px] font-bold uppercase tracking-[.16em] text-ink sm:px-8">Comprar vintage único</Link></section>
</>; }
function Info({icon:Icon,title,text}:{icon:typeof Ruler;title:string;text:string}) { return <div className="border-t border-stone-400 pt-6"><Icon size={20} strokeWidth={1.3}/><h3 className="mt-8 editorial-serif text-2xl">{title}</h3><p className="mt-3 text-xs leading-6 text-stone-500">{text}</p></div>; }
