import { Clock3 } from "lucide-react";
import { NewReservation, CancelReservation } from "@/components/reservation-actions";
import { Badge, PageHeader, statusTone } from "@/components/ui";
import { customers, products } from "@/lib/demo-data";
import { getReservations } from "@/lib/services/reservations";
import { dateTime } from "@/lib/utils";

export default async function ReservationsPage({ searchParams }: { searchParams: Promise<{status?:string}> }) {
  const {status}=await searchParams; const reservations=getReservations(status);
  return <><PageHeader eyebrow="Customer holds" title="Reservations" description="Create and manage short-term product holds for voice and in-store customers." action={<NewReservation customers={customers} products={products}/>}/><div className="mb-5 flex flex-wrap gap-2">{[["","All"],["pending","Pending"],["confirmed","Confirmed"],["cancelled","Cancelled"],["expired","Expired"]].map(([value,label])=><a key={value} href={value?`/reservations?status=${value}`:"/reservations"} className={`rounded-full px-4 py-2 text-xs font-semibold ${status===value||(!status&&!value)?"bg-ink text-white":"border bg-white text-stone-500"}`}>{label}</a>)}</div><div className="table-shell overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="border-b bg-stone-50 text-[10px] uppercase tracking-wider text-stone-400"><tr><th className="px-6 py-4">Reservation</th><th className="px-4 py-4">Customer</th><th className="px-4 py-4">Product</th><th className="px-4 py-4">Expires</th><th className="px-4 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody>{reservations.map(r=><tr key={r.id} className="table-row text-xs"><td className="px-6 py-4"><div className="font-bold">{r.code}</div><div className="mt-1 text-[10px] text-stone-400">Created {dateTime(r.createdAt)}</div></td><td className="px-4 py-4 font-medium">{r.customerName}</td><td className="px-4 py-4"><div className="font-medium">{r.productName}</div><div className="mt-1 text-[10px] text-stone-400">Quantity {r.quantity}</div></td><td className="px-4 py-4"><span className="inline-flex items-center gap-1 text-stone-500"><Clock3 size={13}/>{dateTime(r.expiresAt)}</span></td><td className="px-4 py-4"><Badge tone={statusTone(r.status)}>{r.status}</Badge></td><td className="px-6 py-4 text-right">{(r.status==="pending"||r.status==="confirmed")?<CancelReservation id={r.id}/>:<span className="text-stone-300">—</span>}</td></tr>)}</tbody></table></div></>;
}
