import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ChevronDown, Ruler, ShieldCheck, Sparkles } from "lucide-react";
import { AddToCart } from "@/components/add-to-cart";
import { FavoriteButton } from "@/components/favorite-button";
import { ProductCard } from "@/components/product-card";
import { getProduct, getProducts } from "@/lib/services/products";
import { categoryLabel, colorLabel, materialLabel, money } from "@/lib/utils";

export default async function ProductPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; const product=getProduct(id); if(!product) notFound();
  const available=product.stock-product.reservedStock; const numeric=Number(product.id.replace(/\D/g,""))||1;
  const era=["Finales de los 80","Principios de los 90","Mediados de los 90","Finales de los 90","Principios de los 2000"][numeric%5];
  const condition=["Excelente estado vintage","Muy buen estado vintage","Buen estado vintage"][numeric%3];
  const related=getProducts().filter(item=>item.category===product.category&&item.id!==product.id&&item.stock-item.reservedStock>0).slice(0,4);
  const modelImage=product.image.replace("/products/photos/", "/products/models/").replace(".webp", ".png");
  return <>
    <div className="px-5 py-5 md:px-10"><div className="mx-auto max-w-[1450px]"><Link href="/products" className="inline-flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.14em] text-stone-500"><ArrowLeft size={13}/>Volver a la tienda</Link></div></div>
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[1.45fr_1fr]"><div className="grid grid-cols-2 gap-1 bg-stone-200"><div className="relative aspect-[4/5] bg-[#d9d1c2]"><Image src={product.image} alt={product.name} fill priority className="object-cover"/></div><div className="relative aspect-[4/5] bg-stone-300"><Image src={modelImage} alt={`Modelo usando ${product.name}`} fill className="object-cover"/></div><div className="relative col-span-2 hidden aspect-[16/9] bg-[#cfc5b6] sm:block"><Image src={product.image} alt={`Detalle de ${product.name}`} fill className="object-cover object-[center_35%]"/><div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-black/5"/></div></div>
    <aside className="min-w-0 px-5 py-10 sm:px-6 md:px-12 md:py-16 lg:sticky lg:top-[106px] lg:h-fit"><div className="text-[9px] font-bold uppercase tracking-[.2em] text-rust">{product.brand} · {era}</div><div className="mt-3 flex items-start justify-between gap-4 sm:gap-5"><h1 className="min-w-0 break-words text-balance editorial-serif text-3xl leading-none sm:text-4xl md:text-5xl">{product.name}</h1><FavoriteButton className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-stone-300"/></div><div className="mt-5 text-lg font-semibold">{money(product.price)}</div><p className="mt-7 border-t border-stone-300 pt-7 text-sm leading-7 text-stone-600">{product.description}</p><div className="mt-7"><div className="mb-2 flex flex-wrap justify-between gap-2 text-[9px] font-bold uppercase tracking-[.14em]"><span>Talle seleccionado</span><Link href="/story#sizing" className="flex min-h-8 items-center gap-1 text-stone-400 underline"><Ruler size={12}/>Guía de talles</Link></div><div className="flex h-12 w-16 items-center justify-center border-2 border-ink text-xs font-bold">{product.size}</div></div><AddToCart product={product} className="mt-6 w-full"/><div className="mt-3 text-center text-[9px] uppercase tracking-[.12em] text-stone-400">{available>0?`Solo quedan ${available} · Listo para enviar`:"Esta pieza ya encontró un hogar"}</div><div className="mt-8 divide-y border-y border-stone-300"><Detail label="Detalles y estado"><dl className="grid grid-cols-2 gap-x-3 gap-y-3 text-xs"><dt className="text-stone-400">Época</dt><dd>{era}</dd><dt className="text-stone-400">Estado</dt><dd>{condition}</dd><dt className="text-stone-400">Color</dt><dd className="capitalize">{colorLabel(product.color)}</dd><dt className="text-stone-400">Material</dt><dd>{materialLabel(product.material)}</dd><dt className="text-stone-400">SKU</dt><dd>{product.sku}</dd></dl></Detail><Detail label="Medidas"><p className="text-xs leading-6 text-stone-500">De axila a axila: {48+numeric%10} cm · Largo: {60+numeric%16} cm · Manga: {57+numeric%8} cm. Medido en plano; permití una variación de 1–2 cm.</p></Detail><Detail label="Envíos y devoluciones"><p className="text-xs leading-6 text-stone-500">Despachamos en 1–2 días hábiles. Aceptamos devoluciones dentro de los 14 días, en su estado original.</p></Detail></div><div className="mt-7 grid grid-cols-3 gap-1 text-center sm:gap-2"><Trust icon={ShieldCheck} text="Autenticidad revisada"/><Trust icon={Sparkles} text="Limpieza profesional"/><Trust icon={Ruler} text="Medidas a mano"/></div></aside></div>
    <section className="px-4 py-20 sm:px-5 md:px-10 md:py-28"><div className="mx-auto max-w-[1450px]"><div className="mb-9 flex items-end justify-between"><div><div className="text-[9px] font-bold uppercase tracking-[.2em] text-rust">Más para descubrir</div><h2 className="mt-2 editorial-serif text-3xl sm:text-4xl md:text-5xl">También te puede gustar</h2></div><Link href={`/products?category=${product.category}`} className="hidden text-[9px] font-bold uppercase tracking-wider underline md:block">Ver {categoryLabel(product.category)}</Link></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{related.map(item=><ProductCard key={item.id} product={item}/>)}</div></div></section>
  </>;
}
function Detail({label,children}:{label:string;children:React.ReactNode}) { return <details className="group py-5" open={label==="Detalles y estado"}><summary className="flex cursor-pointer list-none items-center justify-between text-[10px] font-bold uppercase tracking-[.14em]">{label}<ChevronDown size={15} className="transition group-open:rotate-180"/></summary><div className="pt-5">{children}</div></details>; }
function Trust({icon:Icon,text}:{icon:typeof ShieldCheck;text:string}) { return <div className="flex flex-col items-center gap-2 border border-stone-200 p-3"><Icon size={17} strokeWidth={1.3}/><span className="text-[8px] uppercase leading-3 tracking-wider text-stone-500">{text}</span></div>; }
